'use client';

import { useState } from 'react';

export default function Disclaimer() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="bg-yellow-50 border-l-1 border-yellow-400 text-xs text-gray-800 mb-0 rounded-sm py-1 px-2 leading-tight">
      <div className="flex justify-between items-center">
        <h2 className="font-bold text-yellow-800">📢 Results can be incorrect - please read Disclaimer</h2>
        <button
          onClick={() => setIsOpen(!isOpen)}
          className="text-blue-600 text-xs hover:underline ml-4"
        >
          {isOpen ? 'Hide' : 'Show'}
        </button>
      </div>

      {isOpen && (
        <div className="mt-2 leading-relaxed text-sm">
          This tool is intended for informational and educational purposes only. It does not constitute investment advice or a recommendation to buy, sell, or hold any security.
          <br /><br />
          This tool is still in development phase and results can be incorrect. 
          <br /><br />
          Thanks to Yahoo Finance for providing automatic data fetch. Users are recommended to check the data before using it.
          <br /><br />
          Thanks to Screener.in for providing excel download functionality that can help analysing financials of the companies.
          <br /><br />
          All financial analyses, fair value calculations, and projections generated by this platform are based on uploaded data, and the assumptions entered by the user. The results calculations are hypothetical in nature and may differ materially from real-world outcomes.
          <br /><br />
          Stock market investments are subject to market risks. Users are strongly advised to conduct their own research and consult a SEBI-registered investment advisor or research analyst before making any investment decisions.
          <br /><br />
          This platform disclaims any liability for financial losses or decisions made based on the output provided herein.
        </div>
      )}
    </div>
  );
}
